version: "3.3"

services:
  graphqlsrv:
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile-graphqlsrv
    container_name: graphqlsrv
    command: npm run dev
    volumes:
      - ./../server:/server
      - /server/node_modules
    ports:
      - "9000:8080"
    networks:
      graphql:
        aliases:
          - graphqlsrv

  react:
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile-react
    container_name: react
    command: npm start
    volumes:
      - ./../app:/react-graphql
      - /react-graphql/node_modules
    ports:
      - "8000:3000"
    networks:
      graphql:
        aliases:
          - react

  mongo:
    image: mongo:3.7.3-jessie
    container_name: mongo
    ports:
       - "9500:27017"
    networks:
      graphql:
        aliases:
          - mongo

  mongoseed:
    build:
      context: ./../
      dockerfile: docker/Dockerfile-mongoseed
    container_name: mongoseed
    depends_on:
      - mongo
    command: 'bash -c "mongoimport --host mongo:27017 --db graphql --type json --file /seed-data/pokemons.json --jsonArray"'
    networks:
      graphql:
        aliases:
          - mongoseed

networks:
  # CREATE KERING NETWORK
  graphql:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 175.20.20.0/16
